# Rockchip Generic Board
BOARD_NAME="Fast HW Perf Emu Board"
BOARDFAMILY="rockchip-rk3588"
BOARD_MAINTAINER="Sergey Kharenko"
BOOTCONFIG="fhpe_rp_defconfig" # vendor name, not standard, see hook below, set BOOT_SOC below to compensate
BOOT_SOC="rk3588"
KERNEL_TARGET="vendor"
KERNEL_TEST_TARGET="vendor"
FULL_DESKTOP="yes"
BOOT_LOGO="desktop"
BOOT_FDT_FILE="rockchip/rk3588-fhpe-rp.dtb"
BOOT_SCENARIO="spl-blobs"
BOOT_SUPPORT_SPI="yes"
BOOT_SPI_RKSPI_LOADER="yes"
IMAGE_PARTITION_TABLE="gpt"

function late_family_config__fhpe-rp_change_to_npan_config() {
	display_alert "$BOARD" "Change to use linux-rk35xx-vendor-npan.conf" "info"
	
	BOOTSOURCE='https://github.com/SergeyKharenko/u-boot.git'
	BOOTBRANCH='branch:sk-series'
	KERNELSOURCE='https://github.com/SergeyKharenko/linux-rockchip.git'
	LINUXCONFIG="linux-rk35xx-vendor-npan"
	return 0
}

function post_family_tweaks__fhpe-rp_install_custom_packs() {
	display_alert "$BOARD" "Installing Custom Favor Packs" "info"
    # Core development toolchain & build utilities
    chroot_sdcard_apt_get_install \
        wget git curl meson \
        g++ gdb clang \
		gdbserver \
        build-essential \
        cmake cmake-gui ninja-build ccache \
        pkg-config \
        libc6-dev libstdc++-12-dev
}

# "rockchip-common: boot SD card first, then NVMe, then mmc"
# include/configs/rockchip-common.h
# -#define BOOT_TARGETS "mmc1 mmc0 nvme scsi usb pxe dhcp spi"
# +#define BOOT_TARGETS "mmc0 nvme mmc1 scsi usb pxe dhcp spi"
# On nanopct6, mmc0 is the eMMC, mmc1 is the SD card slot
function pre_config_uboot_target__fhpe-rp_patch_rockchip_common_boot_order() {
	declare -a rockchip_uboot_targets=("mmc1" "mmc0" "pxe" "dhcp" "spi") # for future make-this-generic delight
	display_alert "u-boot for ${BOARD}/${BRANCH}" "u-boot: adjust boot order to '${rockchip_uboot_targets[*]}'" "info"
	sed -i -e "s/#define BOOT_TARGETS.*/#define BOOT_TARGETS \"${rockchip_uboot_targets[*]}\"/" include/configs/rockchip-common.h
	regular_git diff -u include/configs/rockchip-common.h || true
}

function post_post_debootstrap_tweaks__fhpe-rp_setup_apt_sources() {
	display_alert "$BOARD" "Configuring APT sources" "info"
	cp -f $SRC/packages/bsp/sk-ifdk/armbian.sources $SDCARD/etc/apt/sources.list.d/
	cp -f $SRC/packages/bsp/sk-ifdk/debian.sources $SDCARD/etc/apt/sources.list.d/
	rm $SDCARD/etc/apt/sources.list.d/armbian-config.sources
}

# Include fw_setenv, configured to point to the correct spot on the SPI Flash
PACKAGE_LIST_BOARD="libubootenv-tool" # libubootenv-tool provides fw_printenv and fw_setenv, for talking to U-Boot environment
